# Run me by typing `mythx analyze` in the directory of the yml file! :)

ci: true
confirm: true
analyze:
    mode: quick
    async: true
    create-group: true
    solc: 0.8.7
    remappings:
        - "@openzeppelin=node_modules/@openzeppelin"
    targets:
        - contracts/token/BeethovenxToken.sol:BeethovenxToken
        - contracts/token/BeethovenxBar.sol:BeethovenxBar
        - contracts/token/BeethovenxMasterChef.sol:BeethovenxMasterChef
        - contracts/governance/Timelock.sol:Timelock
        - contracts/vesting/MasterChefLpTokenTimelock.sol:MasterChefLpTokenTimelock
